"""Persistent MCP stdio client for Cua Driver.

On Linux and Windows a bare `cua-driver mcp` owns its own runtime, so this needs
no separate daemon. Stdlib only.
"""

from __future__ import annotations

import json
import os
import queue
import subprocess
import threading
import time
from pathlib import Path
from typing import Any

from . import host

PROTOCOL_VERSION = "2025-06-18"

#: How long one driver call may take before it is abandoned.
#:
#: A wedged call must not hang the whole MCP tool until the *harness* gives up —
#: which is what happens when a page raises a JS dialog (`alert`/`confirm`/
#: `beforeunload`), because `Runtime.evaluate` then blocks until the dialog is
#: answered and nothing here ever answers it. Observed in a real run: the tool call
#: hung, the harness timed out, and the agent burned steps restarting Chrome.
#: Every single call is sub-second in practice, so this is ~50x margin.
CALL_TIMEOUT_SECONDS = float(os.environ.get("JEV_USE_CALL_TIMEOUT", "30"))

# The Wayland path (AT-SPI + the WinRects GNOME Shell helper) is opt-in. Without
# this the driver uses X11 only and reports zero windows on a native-Wayland
# desktop, even when the helper is installed and ACTIVE. Linux-only by definition:
# on Windows and macOS there is no compositor to cooperate with, and setting it
# there is just noise in the child's environment.
_WAYLAND_ENV = {"CUA_DRIVER_RS_ENABLE_WAYLAND": "1"} if host.IS_LINUX else {}

DRIVER_ENV_DEFAULTS = {
    **_WAYLAND_ENV,
    # -- Why unrestricted mode -------------------------------------------------
    # Driving a browser page requires the `page` tool, and on GNOME/Wayland that is
    # the ONLY browser surface that works: the typed `browser_*` tools need
    # `browser_prepare`, which needs an existing-profile grant or a provable
    # accessibility binding, and a long-running Chrome does not expose one.
    #
    # `page` mutations are gated on unrestricted mode. Measured: setting only
    # CUA_DRIVER_ENABLE_LEGACY_PAGE_MUTATIONS=1 is NOT enough — the driver answers
    # "legacy page mutation is unbounded and requires unrestricted mode with trusted
    # launch-time risk acceptance". So the flag below is genuinely required, not
    # belt-and-braces.
    #
    # Containment: this server spawns its own `cua-driver mcp` process per tool call
    # and owns its stdio, so unrestricted applies to a process that only ever serves
    # our browser tools. Nothing else can reach it. It is still a real widening —
    # the driver would no longer refuse a dangerous action — which is why every
    # script string we send is generated by us and page text is never interpolated.
    "CUA_DRIVER_ENABLE_LEGACY_PAGE_MUTATIONS": "1",
    "CUA_DRIVER_PERMISSION_MODE": "unrestricted",
    "CUA_DRIVER_DANGEROUSLY_BYPASS_APPROVALS": "1",
}


class DriverError(RuntimeError):
    """Raised when the driver cannot be reached or returns an error result."""


def find_driver() -> str:
    """Locate `cua-driver`, or explain how to install it.

    Resolution order lives in `host`: the `CUA_DRIVER_COMMAND` override, then
    PATH, then the directories the installers actually use. That last fallback
    matters most on Windows, where `install.ps1` appends to the *User* PATH —
    a change an already-running process cannot see.
    """
    found = host.find_cua_driver()
    if found:
        return found
    raise FileNotFoundError(
        "cua-driver not found on PATH"
        + ("" if host.IS_WINDOWS else " or at ~/.local/bin/cua-driver")
        + f".\nInstall it with:\n\n    {host.driver_install_hint()}\n"
        + "\nOr set CUA_DRIVER_COMMAND to an existing binary."
    )


class Driver:
    """A persistent `cua-driver mcp` session over stdio."""

    def __init__(
        self,
        command: str | None = None,
        session: str = "jev-use",
        extra_args: list[str] | None = None,
    ) -> None:
        self.command = command or find_driver()
        self.session = session
        self.extra_args = list(extra_args or [])
        self._proc: subprocess.Popen | None = None
        self._next_id = 0
        self._lock = threading.Lock()
        self.stderr_tail: list[str] = []
        #: Lines the stdout reader thread has produced. A queue rather than a bare
        #: `readline()` so a call can be abandoned on a deadline.
        self._lines: queue.Queue[str | None] = queue.Queue()

    # -- lifecycle ---------------------------------------------------------

    def __enter__(self) -> "Driver":
        self.start()
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    def start(self) -> None:
        if self._proc is not None:
            return
        env = dict(os.environ)
        for key, value in DRIVER_ENV_DEFAULTS.items():
            env.setdefault(key, value)
        self._proc = subprocess.Popen(
            [self.command, "mcp", *self.extra_args],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
            env=env,
        )
        self._lines = queue.Queue()
        threading.Thread(target=self._drain_stderr, daemon=True).start()
        threading.Thread(target=self._read_stdout, daemon=True).start()
        self._request(
            "initialize",
            {
                "protocolVersion": PROTOCOL_VERSION,
                "capabilities": {},
                "clientInfo": {"name": "jev-use", "version": "0.1.0"},
            },
        )
        self._notify("notifications/initialized", {})

    @property
    def alive(self) -> bool:
        """True while the child process is still running.

        Used to decide whether a cached session can be reused: a driver that has
        exited would accept a write and then never answer it.
        """
        return self._proc is not None and self._proc.poll() is None

    def close(self) -> None:
        proc, self._proc = self._proc, None
        if proc is None:
            return
        try:
            if proc.stdin:
                proc.stdin.close()
            proc.terminate()
            proc.wait(timeout=5)
        except Exception:
            try:
                proc.kill()
            except Exception:
                pass

    def _drain_stderr(self) -> None:
        proc = self._proc
        if proc is None or proc.stderr is None:
            return
        for line in proc.stderr:
            self.stderr_tail.append(line.rstrip())
            del self.stderr_tail[:-40]

    def _read_stdout(self) -> None:
        """Feed reply lines onto the queue, and a `None` sentinel on EOF.

        A thread rather than a blocking `readline()` in the caller: it is what lets
        `_read_response` give up on a deadline instead of hanging forever.
        """
        proc = self._proc
        if proc is None or proc.stdout is None:
            return
        for line in proc.stdout:
            self._lines.put(line)
        self._lines.put(None)

    # -- protocol ----------------------------------------------------------

    def _write(self, payload: dict[str, Any]) -> None:
        if self._proc is None or self._proc.stdin is None:
            raise DriverError("driver is not running; call start() first")
        try:
            self._proc.stdin.write(json.dumps(payload) + "\n")
            self._proc.stdin.flush()
        except (BrokenPipeError, OSError) as exc:
            # A driver that died mid-session must surface as guidance, not as a raw
            # broken pipe from deep inside the transport.
            detail = "\n".join(self.stderr_tail[-8:]) or "(no stderr)"
            raise DriverError(f"driver is not accepting input ({exc})\n{detail}") from exc

    def _notify(self, method: str, params: dict[str, Any]) -> None:
        self._write({"jsonrpc": "2.0", "method": method, "params": params})

    def _request(self, method: str, params: dict[str, Any]) -> dict[str, Any]:
        with self._lock:
            self._next_id += 1
            request_id = self._next_id
            self._write(
                {"jsonrpc": "2.0", "id": request_id, "method": method, "params": params}
            )
            return self._read_response(request_id)

    def _read_response(self, request_id: int) -> dict[str, Any]:
        deadline = time.monotonic() + CALL_TIMEOUT_SECONDS
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise self._timeout_error(request_id)
            try:
                line = self._lines.get(timeout=remaining)
            except queue.Empty:
                raise self._timeout_error(request_id)
            if line is None:
                detail = "\n".join(self.stderr_tail[-8:]) or "(no stderr)"
                raise DriverError(f"driver closed stdout while awaiting {request_id}\n{detail}")
            line = line.strip()
            if not line:
                continue
            try:
                message = json.loads(line)
            except json.JSONDecodeError:
                continue
            if message.get("id") != request_id:
                continue
            if "error" in message:
                raise DriverError(f"{method_label(message)}: {message['error']}")
            return message.get("result", {})

    def _timeout_error(self, request_id: int) -> DriverError:
        """Abandon a call that never answered, and kill the driver so it is replaced.

        The child is killed and `_proc` cleared, so `alive` is False and the cached
        session is dropped — the next call starts a fresh driver instead of writing
        into a wedged one.
        """
        proc, self._proc = self._proc, None
        if proc is not None:
            try:
                proc.kill()
            except Exception:
                pass
        return DriverError(
            f"driver did not answer {request_id} within {CALL_TIMEOUT_SECONDS:g}s. "
            "The usual cause is a page-owned JavaScript dialog (alert/confirm/"
            "beforeunload) blocking the CDP call. The driver was killed; the next "
            "call starts a fresh one."
        )

    def list_tools(self) -> list[str]:
        result = self._request("tools/list", {})
        return [tool["name"] for tool in result.get("tools", [])]

    def call(self, tool: str, arguments: dict[str, Any] | None = None) -> "ToolResult":
        """Invoke one driver tool. `session` is injected when the tool accepts it."""
        args = dict(arguments or {})
        args.setdefault("session", self.session)
        result = self._request("tools/call", {"name": tool, "arguments": args})

        text = ""
        for block in result.get("content", []):
            if block.get("type") == "text":
                text += block.get("text", "")
        structured = result.get("structuredContent")
        is_error = bool(result.get("isError"))

        if is_error:
            raise DriverError(f"{tool} failed: {text.strip()}")
        return ToolResult(tool=tool, text=text, structured=structured)

    def close_cooperative(self, pid: int) -> None:
        self.call("kill_app", {"pid": pid})


def method_label(message: dict[str, Any]) -> str:
    return message.get("error", {}).get("message", "driver error")


class ToolResult:
    """A driver tool response: human text plus optional structured content."""

    def __init__(self, tool: str, text: str, structured: Any = None) -> None:
        self.tool = tool
        self.text = text
        self.structured = structured

    def json(self) -> Any:
        """Structured content when present, else the parsed text payload."""
        if self.structured is not None:
            return self.structured
        body = self.text.strip()
        if body.startswith("✅"):
            body = body.split("\n", 1)[1] if "\n" in body else ""
        body = body.strip()
        if not body:
            return None
        try:
            return json.loads(body)
        except json.JSONDecodeError:
            return None

    def __repr__(self) -> str:
        return f"ToolResult({self.tool!r}, {self.text.strip()[:60]!r})"
